### Получить всех сотрудников
GET http://localhost:8080/employees

###Создать сотрудника
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "sasha",
  "lastName": "Aleksandrov",
  "department": 1,
  "salary": 1000
}
### Создать сотрудника 2
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Andrey",
  "lastName": "Andreev",
  "department": 2,
  "salary": 3000
}

### Создать сотрудника 3
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Alex",
  "lastName": "Alexandrov",
  "department": 3,
  "salary": 5000
}

### Создать сотрудника 4
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Misha",
  "lastName": "Ivanov",
  "department": 4,
  "salary": 4000
}

### Создать сотрудника 5
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Masha",
  "lastName": "Ivanova",
  "department": 2,
  "salary": 2000
}

### Получить сумму зарплат по сотрудникам
GET http://localhost:8080/employees/salary/sum

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employees/salary/min

### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employees/salary/max

### Получение всех сотрудников, зарплата которых больше средней зарплаты
GET http://localhost:8080/employees/highSalary



### Получить список сотрудников по департаменту
GET http://localhost:8080/department/employees


### Получить сумму зарплат по департаменту
GET http://localhost:8080/department/id/salary/sum


### Получить максимальную зарплату по департаменту
GET http://localhost:8080/department/{{id}}/salary/max


### Получить минимальную зарплату по департаменту
GET http://localhost:8080/department/{{id}}/salary/min


### Получить сотрудников, сгрупированных по отделам
GET http://localhost:8080/department/employees/grouped


